import {ICONS, MENU_ICONS} from "../constants";
import {
    MdHome,
    MdWeb,
    MdSearch,
    MdHelp,
    MdArrowDropUp,
    MdArrowDropDown,
    MdArrowBack,
    MdKeyboardArrowDown,
    MdList,
    MdVerifiedUser,
    MdPeople,
    MdLibraryBooks,
    MdSettings,
    MdDvr,
    MdDesktopMac,
    MdCheck,
    MdIndeterminateCheckBox,
    MdKeyboardArrowLeft,
    MdCheckBoxOutlineBlank,
    MdFirstPage,
    MdLastPage,
    MdChevronLeft,
    MdChevronRight,
    MdEdit,
    MdLanguage,
    MdExitToApp,
    MdVisibility,
    MdVisibilityOff,
    MdAdd, MdRadioButtonChecked, MdRadioButtonUnchecked
} from 'react-icons/md';
import {IoMdRadioButtonOff, IoMdRadioButtonOn} from "react-icons/io";

export default {
    [ICONS.ARROW_UP]: MdArrowDropUp,
    [ICONS.ARROW_DOWN]: MdKeyboardArrowDown,
    [ICONS.SEARCH]: MdSearch,
    [ICONS.EDIT]: MdEdit,
    [ICONS.CHECK]: MdCheck,
    [ICONS.LANG]: MdLanguage,
    [ICONS.ADD]: MdAdd,
    [ICONS.CHECK_FALSE]: MdIndeterminateCheckBox,
    [ICONS.LEFT]: MdKeyboardArrowLeft,
    [ICONS.RADIO_TRUE]: IoMdRadioButtonOn,
    [ICONS.RADIO_FALSE]: IoMdRadioButtonOff,
    [ICONS.CHECK_OUTLINE_FALSE]: MdCheckBoxOutlineBlank,
    [ICONS.LAST_PAGE]: MdLastPage,
    [ICONS.FIRST_PAGE]: MdFirstPage,
    [ICONS.LEFT_PAGE]: MdChevronLeft,
    [ICONS.EXIT]: MdExitToApp,
    [ICONS.VISIBILITY]: MdVisibility,
    [ICONS.VISIBILITY_OFF]: MdVisibilityOff,
    [ICONS.RIGHT_PAGE]: MdChevronRight,
    [MENU_ICONS.HOME]: MdHome,
    [MENU_ICONS.LIST]: MdList,
    [MENU_ICONS.USERS]: MdPeople,
    [MENU_ICONS.PAGES]: MdWeb,
    [MENU_ICONS.SETTINGS]: MdSettings,
    [MENU_ICONS.DOC]: MdLibraryBooks,
    [MENU_ICONS.FORMS]: MdDvr,
    [MENU_ICONS.ELEMENTS]: MdDesktopMac,
}