import {ICONS, MENU_ICONS} from "../constants";
import {
    MdHome,
    MdWeb,
    MdSearch,
    MdHelp,
    MdArrowDropUp,
    MdArrowDropDown,
    MdArrowBack,
    MdKeyboardArrowDown,
    MdList,
    MdVerifiedUser,
    MdPeople,
    MdLibraryBooks,
    MdSettings,
    MdDvr,
    MdDesktopMac,
    MdCheck,
    MdIndeterminateCheckBox,
    MdKeyboardArrowLeft,
    MdCheckBoxOutlineBlank,
    MdFirstPage,
    MdLastPage,
    MdChevronLeft,
    MdChevronRight,
    MdEdit
} from 'react-icons/md';

export default {
    [ICONS.ARROW_UP]: MdArrowDropUp,
    [ICONS.ARROW_DOWN]: MdKeyboardArrowDown,
    [ICONS.SEARCH]: MdSearch,
    [ICONS.EDIT]: MdEdit,
    [ICONS.CHECK]: MdCheck,
    [ICONS.CHECK_FALSE]: MdIndeterminateCheckBox,
    [ICONS.LEFT]: MdKeyboardArrowLeft,
    [ICONS.CHECK_OUTLINE_FALSE]: MdCheckBoxOutlineBlank,
    [ICONS.LAST_PAGE]: MdLastPage,
    [ICONS.FIRST_PAGE]: MdFirstPage,
    [ICONS.LEFT_PAGE]: MdChevronLeft,
    [ICONS.RIGHT_PAGE]: MdChevronRight,
    [MENU_ICONS.HOME]: MdHome,
    [MENU_ICONS.LIST]: MdList,
    [MENU_ICONS.USERS]: MdPeople,
    [MENU_ICONS.PAGES]: MdWeb,
    [MENU_ICONS.SETTINGS]: MdSettings,
    [MENU_ICONS.DOC]: MdLibraryBooks,
    [MENU_ICONS.FORMS]: MdDvr,
    [MENU_ICONS.ELEMENTS]: MdDesktopMac,


}